export const RELATIONSHIP_GOALS = [
  {
    title: "Dating 👩‍❤️‍👨",
    subtitle:
      "Seeking love and meaningful connections? Choose dating for genuine relationships.",
  },
  {
    title: "Friendship 🙌",
    subtitle:
      "Expand your social circle and make new friends. Opt for friendship today.",
  },

  {
    title: "Serious Relationship 💍",
    subtitle:
      "Ready for commitment and a lasting partnership? Pick serious relationship.",
  },
];

export const INTERESTS = [
  "Travel ✈️",
  "Cooking 🍳",
  "Hiking 🏞️",
  "Yoga 🧘",
  "Gaming 🎮",
  "Movies 🎥",
  "Photography 📷",
  "Music 🎵",
  "Pets 🐱",
  "Painting 🎨",
  "Art 🎨",
  "Fitness 💪",
  "Reading 📖",
  "Dancing 💃",
  "Sports 🏀",
  "Board Games 🎲",
  "Technology 📱",
  "Fashion 👗",
  "Motorcycling 🏍️",
  "Science 🔬",
  "History 📜",
  "Nature 🌿",
  "Adventure 🌄",
  "Gardening 🌻",
  "Foodie 🍽️",
  "Writing ✍️",
  "Poetry 📝",
  "Astronomy 🔭",
  "Sustainable Living 🌱",
  "Film Production 🎬",
  "Meditation 🧘‍♂️",
  "Comedy 😄",
  "Volunteering 🤝",
  "DIY Projects 🛠️",
  "Art History 🏛️",
  "Philosophy 🧠",
  "Snowboarding 🏂",
  "Wine Tasting 🍷",
  "Collectibles 🎩",
  "Sailing ⛵",
  "Karaoke 🎤",
  "Surfing 🏄",
  "Scuba Diving 🌊",
  "Skydiving 🪂",
  "Pottery 🏺",
  "Wildlife Conservation 🦁",
  "Ghost Hunting 👻",
  "Geocaching 🌐",
  "Stand-up Comedy 🎙️",
  "Motor Racing 🏁",
  "Paranormal Investigation 🕵️‍♂️",
];
